### ISSUE TITLE
os.tmpDir() is deprecated

### ISSUE THREAD

**Issue by ceemonkey** [yrammos/AtLilyPond#6]
Running Atom 1.22.1 x64 on Arch 4.14.5-1. Installation of AtLilyPond 1.2.0 fails. Error log from Atom below:

```
(node:2889) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

fs.js:663
  return binding.open(pathModule.toNamespacedPath(path),
                 ^

Error: ENOENT: no such file or directory, open '/home/ccosas/.atom/packages/AtLilyPond/package.json'
    at Object.fs.openSync (fs.js:663:18)
    at Proxy.fs.readFileSync (fs.js:568:33)
    at Proxy.fs.readFileSync (/usr/lib/node_modules/atom-package-manager/node_modules/asar-require/lib/require.js:86:27)
    at /usr/lib/node_modules/atom-package-manager/lib/install.js:476:42
    at fn (/usr/lib/node_modules/atom-package-manager/node_modules/async/lib/async.js:582:34)
    at Immediate.<anonymous> (/usr/lib/node_modules/atom-package-manager/node_modules/async/lib/async.js:498:34)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)
```

**Comment by yrammos** [comment]
Thank you for the alert, Christian. I'm far too busy with other priorities
right now, but I'll address it.

**Comment by ceemonkey** [comment]
No worries and no real rush — ran across it while distro hopping. Still getting a lot of mileage out of AtLilyPond on Ubuntu where it works like a charm. That's part of the danger with rolling releases: Things _will_ break!

**Comment by Alhadis** [comment]
@ceemonkey Looking at the stack trace suggests the cause of the problem is with `atom-package-manager`, not with this package. In fact, there isn't any executable code here whatsoever! My guess is that this package triggered the error with `atom-package-manager` because `AtLilyPond` was first on your list of installed/active packages, owing to case-sensitive alphabetisation.

**Comment by yrammos** [comment]
I'm inclined to agree with @Alhadis. @ceemonkey, shall I go ahead and close this?

**Comment by ceemonkey** [comment]
Yes, that’s fine. Thanks to you both for your attention and help.
